name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      -
        run: npm install
      -
        run: npm run lint
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14.x, 12.x, 10.x]
        exclude:
          -
            node-version: 14.x
            os: ubuntu-latest
          -
            node-version: 10.x
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -
        run: npm install
      -
        run: npm test
